#drop tables
drop_linestarapp_table = '''
    DROP TABLE IF EXISTS {}_linestarapp_{}
'''
drop_sportsline_table = '''
    DROP TABLE IF EXISTS {}_sportsline_{}
'''

#sportsline articles from dfs pro
sportsline_pro_create_table = '''
    CREATE TABLE IF NOT EXISTS {}_sportsline_pro (
        primary_id SERIAL PRIMARY KEY,
        link_pro VARCHAR,
        title_pro VARCHAR,
        date_pro VARCHAR,
        name VARCHAR,
        dfs_pick_dk INT
    )
'''

#sportsline articles that have rankings only
sportsline_lead_create_table = '''
    CREATE TABLE IF NOT EXISTS {}_sportsline_lead (
        primary_id SERIAL PRIMARY KEY,
        link_lead VARCHAR,
        title_lead VARCHAR,
        date_lead VARCHAR,
        name VARCHAR,
        pos_lead INT
    )
'''

#sportsline articles that have rankings and odds
sportsline_bet_create_table = '''
    CREATE TABLE IF NOT EXISTS {}_sportsline_bet (
        primary_id SERIAL PRIMARY KEY,
        link_bet VARCHAR,
        title_bet VARCHAR,
        date_bet VARCHAR,
        name VARCHAR,
        pos_bet INT,
        pos_odds_bet FLOAT
    )
'''

#nascar linestarapp
nascar_linestarapp_create_table = '''
    CREATE TABLE IF NOT EXISTS nascar_linestarapp_{} ( 
        primary_id SERIAL PRIMARY KEY, 
        event_id INT, 
        s INT, 
        player_id INT, 
        name VARCHAR, 
        pos VARCHAR, 
        sal NUMERIC, 
        gid NUMERIC, 
        gi VARCHAR, 
        date VARCHAR, 
        ppg NUMERIC, 
        pp NUMERIC, 
        ps NUMERIC, 
        ss NUMERIC, 
        stat NUMERIC, 
        is_ NUMERIC, 
        notes VARCHAR, 
        floor NUMERIC, 
        ceil NUMERIC, 
        conf NUMERIC, 
        ptid NUMERIC, 
        otid NUMERIC, 
        htid NUMERIC, 
        oe VARCHAR, 
        opprank NUMERIC, 
        opptotal NUMERIC, 
        dspid NUMERIC, 
        dgid NUMERIC, 
        img VARCHAR, 
        pteam VARCHAR, 
        hteam VARCHAR, 
        oteam VARCHAR, 
        lock NUMERIC, 
        id NUMERIC, 
        salaryid NUMERIC, 
        owned NUMERIC, 
        hatecount NUMERIC, 
        lovecount NUMERIC,
        races_0 NUMERIC, 
        wins_0 NUMERIC, 
        top_fives_0 NUMERIC, 
        top_tens_0 NUMERIC, 
        avg_finish_0 NUMERIC, 
        laps_led_race_0 NUMERIC, 
        fastest_laps_race_0 NUMERIC, 
        avg_pass_diff_0 NUMERIC, 
        quality_passes_race_0 NUMERIC, 
        fppg_0 NUMERIC, 
        practice_laps_1 NUMERIC, 
        practice_best_lap_time_1 NUMERIC, 
        practice_best_lap_speed_1 NUMERIC, 
        qualifying_pos_1 NUMERIC, 
        qualifying_best_lap_time_1 NUMERIC, 
        qualifying_best_lap_speed_1 NUMERIC, 
        laps_2 NUMERIC,
        miles_2 NUMERIC, 
        surface_2 VARCHAR, 
        restrictor_plate_2 VARCHAR, 
        cautions_race_2 NUMERIC, 
        races_3 NUMERIC, 
        finished_3 NUMERIC, 
        wins_3 NUMERIC, 
        top_5s_3 NUMERIC, 
        top_10s_3 NUMERIC, 
        avg_place_3 NUMERIC, 
        races_4 NUMERIC, 
        finished_4 NUMERIC, 
        wins_4 NUMERIC, 
        top_5s_4 NUMERIC, 
        top_10s_4 NUMERIC, 
        avg_place_4 NUMERIC, 
        projections VARCHAR
    )
'''

lol_linestarapp_create_table = '''
    CREATE TABLE IF NOT EXISTS lol_linestarapp_{} ( 
        primary_id SERIAL PRIMARY KEY, 
        event_id INT, 
        s INT, 
        player_id INT, 
        name VARCHAR, 
        pos VARCHAR, 
        sal NUMERIC, 
        gid NUMERIC, 
        gi VARCHAR, 
        date VARCHAR, 
        ppg NUMERIC, 
        pp NUMERIC, 
        ps NUMERIC, 
        ss NUMERIC, 
        stat NUMERIC, 
        is_ NUMERIC, 
        notes VARCHAR, 
        floor NUMERIC, 
        ceil NUMERIC, 
        conf NUMERIC, 
        ptid NUMERIC, 
        otid NUMERIC, 
        htid NUMERIC, 
        oe VARCHAR, 
        opprank NUMERIC, 
        opptotal NUMERIC, 
        dspid NUMERIC, 
        dgid NUMERIC, 
        img VARCHAR, 
        pteam VARCHAR, 
        hteam VARCHAR, 
        oteam VARCHAR, 
        lock NUMERIC, 
        id NUMERIC, 
        salaryid NUMERIC, 
        owned NUMERIC, 
        hatecount NUMERIC, 
        lovecount NUMERIC,
        best_of_0 NUMERIC, 
        odds_0 NUMERIC, 
        fppg_vs_opp_0 NUMERIC, 
        matchplay_1 NUMERIC,
        game_win_1 NUMERIC,
        fppg_1 NUMERIC,
        kills_g_1 NUMERIC,
        assists_g_1 NUMERIC,
        kills_assts_g_1 NUMERIC,
        deaths_g_1 NUMERIC,
        k_d_1 NUMERIC,
        k_a_d_1 NUMERIC,
        cs_g_1 NUMERIC,
        matchplay_2 NUMERIC,
        game_win_2 NUMERIC,
        fppg_2 NUMERIC,
        kills_g_2 NUMERIC,
        assists_g_2 NUMERIC,
        kills_assts_g_2 NUMERIC,
        deaths_g_2 NUMERIC,
        k_d_2 NUMERIC,
        k_a_d_2 NUMERIC,
        cs_g_2 NUMERIC,
        projections VARCHAR
    )
'''

#pga linestarapp
pga_linestarapp_create_table = '''
    CREATE TABLE IF NOT EXISTS pga_linestarapp_{} ( 
        primary_id SERIAL PRIMARY KEY, 
        event_id INT, 
        s INT, 
        player_id INT, 
        name VARCHAR, 
        pos VARCHAR, 
        sal NUMERIC, 
        gid NUMERIC, 
        gi VARCHAR, 
        date VARCHAR, 
        ppg NUMERIC, 
        pp NUMERIC, 
        ps NUMERIC, 
        ss NUMERIC, 
        stat NUMERIC, 
        is_ NUMERIC, 
        notes VARCHAR, 
        floor NUMERIC, 
        ceil NUMERIC, 
        conf NUMERIC, 
        ptid NUMERIC, 
        otid NUMERIC, 
        htid NUMERIC, 
        oe VARCHAR, 
        opprank NUMERIC, 
        opptotal NUMERIC, 
        dspid NUMERIC, 
        dgid NUMERIC, 
        img VARCHAR, 
        pteam VARCHAR, 
        hteam VARCHAR, 
        oteam VARCHAR, 
        lock NUMERIC, 
        id NUMERIC, 
        salaryid NUMERIC,
        owned NUMERIC,
        hatecount NUMERIC,
        lovecount NUMERIC,
        events_0 NUMERIC,
        wins_0 NUMERIC,
        top_5s_0 NUMERIC,
        top_10s_0 NUMERIC,
        avg_place_0 NUMERIC,
        cuts_made_0 NUMERIC,
        cut_made_0 NUMERIC,
        vegas_odds_0 NUMERIC,
        vegas_value_0 NUMERIC,
        events_1 NUMERIC,
        wins_1 NUMERIC,
        top_5s_1 NUMERIC,
        top_10s_1 NUMERIC,
        avg_place_1 NUMERIC,
        cuts_made_1 NUMERIC,
        cut_made_1 NUMERIC,
        events_2 NUMERIC,
        wins_2 NUMERIC,
        top_5s_2 NUMERIC,
        top_10s_2 NUMERIC,
        avg_place_2 NUMERIC,
        cuts_made_2 NUMERIC,
        cut_made_2 NUMERIC,
        gir_2 NUMERIC,
        driving_acc_2 NUMERIC,
        driving_dist_2 NUMERIC,
        putting_avg_2 NUMERIC,
        scramble_2 NUMERIC,
        events_3 NUMERIC, 
        avg_place_3 NUMERIC,
        cuts_made_3 NUMERIC,
        cut_made__3 NUMERIC,
        gir_3 NUMERIC,
        driving_acc_3 NUMERIC, 
        driving_dist_3 NUMERIC,
        putting_avg_3 NUMERIC,
        scramble_3 NUMERIC,
        projections VARCHAR
    )
'''

#nba linestarapp
nba_linestarapp_create_table = '''
    CREATE TABLE IF NOT EXISTS nba_linestarapp_{} ( 
        primary_id SERIAL PRIMARY KEY, 
        event_id INT, 
        s INT, 
        player_id INT, 
        name VARCHAR, 
        pos VARCHAR, 
        sal NUMERIC, 
        gid NUMERIC, 
        gi VARCHAR, 
        date VARCHAR, 
        ppg NUMERIC, 
        pp NUMERIC, 
        ps NUMERIC, 
        ss NUMERIC, 
        stat NUMERIC, 
        is_ NUMERIC, 
        notes VARCHAR, 
        floor NUMERIC, 
        ceil NUMERIC, 
        conf NUMERIC, 
        ptid NUMERIC, 
        otid NUMERIC, 
        htid NUMERIC, 
        oe VARCHAR, 
        opprank NUMERIC, 
        opptotal NUMERIC, 
        dspid NUMERIC, 
        dgid NUMERIC, 
        img VARCHAR, 
        pteam VARCHAR, 
        hteam VARCHAR, 
        oteam VARCHAR, 
        lock NUMERIC, 
        id NUMERIC,
        salary_id NUMERIC,
        owned NUMERIC,
        hatecount NUMERIC,
        lovecount NUMERIC,
        pts_g_0 NUMERIC,
        reb_g_0 NUMERIC,
        ast_g_0 NUMERIC,
        stl_blk_g_0 NUMERIC,
        mins_g_0 NUMERIC,
        impact_est_0 NUMERIC,
        usage_0 NUMERIC,
        fppm_0 NUMERIC,
        fppg_0 NUMERIC,
        home_away_0 NUMERIC,
        fav_dog_0 NUMERIC,
        pts_g_1 NUMERIC,
        reb_g_1 NUMERIC,
        ast_g_1 NUMERIC,
        stl_blk_g_1 NUMERIC,
        mins_g_1 NUMERIC,
        impact_est_1 NUMERIC,
        usage_1 NUMERIC,
        fppm_1 NUMERIC,
        fppg_1 NUMERIC,
        home_away_1 NUMERIC,
        fav_dog_1 NUMERIC,
        pts_g_2 NUMERIC,
        reb_g_2 NUMERIC,
        ast_g_2 NUMERIC,
        stl_blk_g_2 NUMERIC,
        mins_g_2 NUMERIC,
        impact_est_2 NUMERIC,
        usage_2 NUMERIC,
        fppm_2 NUMERIC,
        fppg_2 NUMERIC,
        home_away_2 NUMERIC,
        fav_dog_2 NUMERIC,
        pts_g_3 NUMERIC,
        reb_g_3 NUMERIC,
        ast_g_3 NUMERIC,
        stl_blk_g_3 NUMERIC,
        mins_g_3 NUMERIC,
        impact_est_3 NUMERIC,
        usage_3 NUMERIC,
        fppm_3 NUMERIC,
        fppg_3 NUMERIC,
        home_away_3 NUMERIC,
        fav_dog_3 NUMERIC,
        pts_g_4 NUMERIC,
        reb_g_4 NUMERIC,
        ast_g_4 NUMERIC,
        stl_g_4 NUMERIC,
        blk_g_4 NUMERIC,
        plus_minus_4 NUMERIC,
        overall_rank_4 NUMERIC,
        fppg_4 NUMERIC,
        home_away_4 NUMERIC,
        fav_dog_4 NUMERIC,
        pts_g_5 NUMERIC,
        reb_g_5 NUMERIC,
        ast_g_5 NUMERIC,
        stl_g_5 NUMERIC,
        blk_g_5 NUMERIC,
        plus_minus_5 NUMERIC,
        overall_rank_5 NUMERIC,
        fppg_5 NUMERIC,
        home_away_5 NUMERIC,
        fav_dog_5 NUMERIC,
        pts_g_6 NUMERIC,
        reb_g_6 NUMERIC,
        ast_g_6 NUMERIC,
        stl_g_6 NUMERIC,
        blk_g_6 NUMERIC,
        plus_minus_6 NUMERIC,
        overall_rank_6 NUMERIC,
        fppg_6 NUMERIC,
        home_away_6 NUMERIC,
        fav_dog_6 NUMERIC,
        pts_g_7 NUMERIC,
        reb_g_7 NUMERIC,
        ast_g_7 NUMERIC,
        stl_g_7 NUMERIC,
        blk_g_7 NUMERIC,
        plus_minus_7 NUMERIC,
        overall_rank_7 NUMERIC,
        fppg_7 NUMERIC,
        home_away_7 NUMERIC,
        fav_dog_7 NUMERIC,
        pts_g_8 NUMERIC,
        reb_g_8 NUMERIC,
        ast_g_8 NUMERIC,
        stl_g_8 NUMERIC,
        blk_g_8 NUMERIC,
        plus_minus_8 NUMERIC,
        overall_rank_8 NUMERIC,
        fppg_8 NUMERIC,
        home_away_8 NUMERIC,
        fav_dog_8 NUMERIC,
        pts_g_9 NUMERIC,
        reb_g_9 NUMERIC,
        ast_g_9 NUMERIC,
        stl_g_9 NUMERIC,
        blk_g_9 NUMERIC,
        plus_minus_9 NUMERIC,
        overall_rank_9 NUMERIC,
        fppg_9 NUMERIC,
        home_away_9 NUMERIC,
        fav_dog_9 NUMERIC,
        pts_g_10 NUMERIC,
        reb_g_10 NUMERIC,
        ast_g_10 NUMERIC,
        stl_g_10 NUMERIC,
        blk_g_10 NUMERIC,
        pace_10 NUMERIC,
        pace_diff_10 NUMERIC,
        overall_rank_10 NUMERIC,
        fppg_10 NUMERIC,
        home_away_10 NUMERIC,
        fav_dog_10 NUMERIC,
        projections VARCHAR
    )
'''
